version: "3"

services:
  proxy:
    build: "./proxy"
    ports:
      - 80:80
      - 443:443
    networks:
      front:
        ipv4_address: 10.80.55.2
  frontend:
    build: "./frontend"
    networks:
      front:
        ipv4_address: 10.80.55.3
  api:
    build: "./api"
    privileged: true
    networks:
      front:
        ipv4_address: 10.80.55.4
  buzz:
    build: "./buzz"
    privileged: true
    networks:
      front:
        ipv4_address: 10.80.55.5

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.80.55.0/24
          gateway: 10.80.55.1